[feat/saved_state_viewmodel]: savedStateHandler를 viewmodel에서 활용하기
TeamPophory/pophory-android pull request #123
Opened 2023-07-09 07:32 UTC by KwakEuiJin

커밋 네이밍이 잘못올라갔슴다..

Response 객체를 벗겨내는 걸 깜빡하고 개발했네요. 어쩐지 다 성공으로 들어오더라고요 ㅋㅋ..

2023-07-09 07:39 UTC, librarywon commented
LGTM 🫡

2023-07-09 08:01 UTC, l2hyunwoo requested changes

2023-07-09 08:01 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/data/network/service/AlbumService.kt
> +    )
이거 지우면 아마 fatal exception 뜰 수 없습니다. NO_CONTENT response가 오는 경우에 대응하기 위한 것이어서 그런데 혹시 모든 요청 실패에 onSuccess를 타나요?

2023-07-09 08:01 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailViewModel.kt
> +    }
init으로 뺄 수 있을 것 같습니다

2023-07-09 08:01 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailActivity.kt
> +                    viewModel.setData()
그럼 여기 삭제 가능

2023-07-09 11:39 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/data/network/service/AlbumService.kt
> +    )
넵넵 Respose<Unit>으로 반환값을 정의시 404의 경우에도 runcatching시에 onSuccess를 타고있습니다.

2023-07-09 11:40 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailViewModel.kt
> +    }
State패턴을 사용하여 초기화쪽에 setData를 쓰기보다는 private한 함수로 선언 후 init 블럭에서 호출하는 것이 더 좋은 방법인것일까요?!

2023-07-09 11:40 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailActivity.kt
> +                    viewModel.setData()
아하!

2023-07-09 11:47 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/data/network/service/AlbumService.kt
> +    )
t....q 저거 그러면 중간에 repository layer에서 response.isSuccessful 한번 처리한다음에 true면 그냥 내려보내고 false면 httpexception  타는 형태로 내려줘야겠네요

2023-07-09 13:38 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/data/network/service/AlbumService.kt
> +    )
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 방법을 조금 더 생각해보고 수정하겠읍니다...

2023-07-11 06:05 UTC, l2hyunwoo requested changes
한번 더 봐주세요

2023-07-11 06:05 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailViewModel.kt
> +    val photoDetailInfo: LiveData<PhotoDetailInfo> get() = _photoDetailInfo
```suggestion
    private val _photoDetail = MutableLiveData<PhotoDetail>()
    val photoDetail: LiveData<PhotoDetail> get() = _photoDetail
```

Detail, Info 모두 비슷한 의미 지니고 있어서 하나만 사용해도 될듯. 근데 Info는 너무 추상적인 의미여서(Data랑 거의 같은 범주) 웬만하면 사용을 지양하면 좋을 것 같음

2023-07-11 06:05 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailViewModel.kt
> +    )
이건 feature내 model 패키지에 넣어도 될 것 같아

2023-07-11 06:06 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/network/PhotoNetworkDataSource.kt
> +    ): Unit?
Service에서 직접 레포지토리를 참조하기보다는 데이터소스를 통해 데이터를 한번 더 가공하는게 Response<Unit>의 형태에서는 더욱 좋은 방법이라고 생각했습니다 하핳 근데 레포지토리 구현체에서 runcatcing으로 반환해도 무방하다면 해당 분리 파일은 제거하겠습니다

2023-07-11 06:06 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/network/PhotoNetworkDataSource.kt
> +    ): Unit?
일관적으로 view단에서는 onSuccess 와 onFailure만을 통해 UI에서 사용하고 싶었어요!

2023-07-11 06:07 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailViewModel.kt
> +    )
넵!

2023-07-11 06:07 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDetailViewModel.kt
> +    val photoDetailInfo: LiveData<PhotoDetailInfo> get() = _photoDetailInfo
사용 지양하기 메모...📝

2023-07-11 06:23 UTC, l2hyunwoo approved these changes
👍🏻

2023-07-11 06:35 UTC, merged