[feature/home_reselected]: fragment 전환 방식변경
TeamPophory/pophory-android pull request #137
Opened 2023-07-11 11:17 UTC by librarywon

## 이슈 코드 

- close #136

## 📸 
[Screen_recording_20230711_201642.webm](https://github.com/TeamPophory/pophory-android/assets/52442547/39c24f19-d201-4bf2-a1a9-ac4af36cbf36)
스크린샷

## 🍀 관련 이슈
- 2차 스프린트 store와 mypage뷰를 고려하였을 때 replace() 대신 메모리를 유지하는 hide(), show() 방식을 채택하여도 성능에 큰 문제가 되지 않을 것으로 생각해 로직을 수정하였습니다.

2023-07-11 11:23 UTC, l2hyunwoo reviewed
이게 예전에 제가 회사에 있을 때 문제가 발생한 적이 있어서 우선 어프루브는 누르지 않을게요.

Show와 hide를 하는 경우, 바텀 탭을 빠르게 왕복할 때 현재 띄워지는 화면 밑에 이전 화면이 그대로 남는 경우가 있어서 문제가 되었습니다.(원래 화면을 투명도 없는 흰색으로 두어도 그런 문제가
발생했름)

그래서 웬만하면 이런 로직을 사용하지 않으려고 했지만, 아직 그런 현상이 테스트에서 눈에 띄지 않았다는 점, 저희 minSdk가 생각보다 꽤 높아서 그런 문제사 발생할 확률이 적다는 점을 생각하면 괜찮을 수도 있을 것 같은데 이건 한번 논의해보죠. 

cc. @KwakEuiJin @jihyeonAnAn

2023-07-11 11:28 UTC, l2hyunwoo requested changes

2023-07-11 11:28 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
> +    private val fragmentMap = mapOf(
프래그먼트를 변수를 통해 참조할 수 있는 형태로는 두지 않는 것이 좋습니다. 특히 멤버변수로 두는건 더더욱…

2023-07-11 11:36 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
> +    private val fragmentMap = mapOf(
넵 알겠습니다!!

2023-07-11 13:04 UTC, KwakEuiJin commented
@librarywon 요거 저의 SOPT 과제처럼 ReSelected 시 무시하는걸로 변경 부탁드립니다

2023-07-11 17:41 UTC, KwakEuiJin requested changes

2023-07-11 17:41 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/HomeActivity.kt
> +
넵  [setOnItemReselectedListener](https://developer.android.com/reference/com/google/android/material/navigation/NavigationBarView.OnItemReselectedListener)사용하시면 될 것 같습니다. 해당 클릭이 들어왔을 때 리턴시켜버리면 될 것 같습니다

2023-07-11 17:42 UTC, KwakEuiJin approved these changes

2023-07-12 02:15 UTC, l2hyunwoo approved these changes

2023-07-12 06:22 UTC, merged