Feature refactor signup
TeamPophory/pophory-android pull request #157
Opened 2023-07-14 02:07 UTC by jihyeonAnAn

## 이슈 코드 

- close #156 

## 📸 스크린샷

## 🍀 관련 이슈
우선 navigation으로 변경했고 navigation viewmodel 사용하면서 추가 수정 예정

2023-07-14 02:12 UTC, l2hyunwoo requested changes
아직 수정중인 것 같은데...리뷰 답니당

2023-07-14 02:12 UTC, l2hyunwoo commented on app/build.gradle.kts
> +    implementation("androidx.navigation:navigation-ui-ktx:2.6.0")
libs에다가 선언해주세요! (이거 분명히 경고 떴을텐데)

2023-07-14 02:12 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
> +    //TODO 수정 필요
👍🏻

2023-07-14 02:12 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
> +//    private fun observeEvent() {
주석 안 사용하면 삭제 고고

2023-07-14 02:12 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/signup/SignUpFirstFragment.kt
>                  } else if (it.toString().length < 2) {
여기도!

2023-07-14 02:12 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/signup/SignUpViewModel.kt
> +    }
이친구 사용하는 곳이 있을까? 어떤 용도로 만든걸까요?

2023-07-14 02:13 UTC, l2hyunwoo commented
아직 코드 수정중인 것 같아서 Draft 걸겠습니다 @jihyeonAnAn

2023-07-14 02:25 UTC, KwakEuiJin reviewed
완성본 내놔~~~ 못참겠다...

2023-07-14 02:25 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
>              }
워후 enum과 when문이라니 이젠 절정 고수의 반열에 들었구나 지현아...

2023-07-14 02:25 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/signup/SignUpFirstFragment.kt
> +                signUpViewModel.setButtonState(!binding.editTvName.text.isNullOrEmpty() && !binding.tvErrorMessage.isVisible)
여기 Boolean값을 반환하는 함수로 따로 빼면 가독성이 더 좋아질 것 같아요

2023-07-14 05:11 UTC, librarywon reviewed
포포리의 자랑 안지현 화이팅

2023-07-14 05:11 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
>              }
미쳤다 돌았따

2023-07-14 05:11 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
> +    }
Fragment관리 멋져요!

2023-07-14 05:11 UTC, librarywon commented on app/src/main/res/layout/activity_sign_up.xml
> +        android:id="@+id/nav_host_fragment"
nav_sign_up_fragment는 어떤가요?

2023-07-14 05:11 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
> +        //기기 뒤로 가기 버튼
친절한 주석 때문에 가독성이 진짜 좋아지는 것 같습니다!

2023-07-19 13:19 UTC, l2hyunwoo requested changes
한번만 더 수정해봅시다

2023-07-19 13:19 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/signup/SignUpFirstFragment.kt
> +        background: Int,
```suggestion
        @DrawableRes background: Int,
```

2023-07-19 13:19 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/signup/adapter/SignUpViewPagerAdapter.kt
> +    //private val buttonState: OnButtonStateChangeListener
안 사용하면 삭제 부탁드립니다

2023-07-19 13:19 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/signup/adapter/SignUpViewPagerAdapter.kt
> +                    //setSignUpButtonInterface(buttonState)
안 사용하면 삭제 고고

2023-07-19 13:19 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/signup/adapter/SignUpViewPagerAdapter.kt
> +                    //setSignUpButtonInterface(buttonState)
위에도 그렇고 이것도 보니까 그냥 apply 삭제해도 될듯?

2023-07-19 13:59 UTC, l2hyunwoo approved these changes
고생했어 지현아

2023-07-19 13:59 UTC, merged