[Feature/mypage] 2차 스프린트 mypage 수정
TeamPophory/pophory-android pull request #158
Opened 2023-07-14 06:16 UTC by librarywon

## 이슈 코드 

- close #146 

## 📸 스크린샷
<img width="394" alt="스크린샷 2023-07-14 오후 3 14 13" src="https://github.com/TeamPophory/pophory-android/assets/52442547/ee3a0ef1-c81b-4464-8ad4-576590b37e09">

## 🍀 관련 이슈
- 2차 api가 나오면 네트워크 관련 로직도 수정하겠습니다!

2023-07-15 06:56 UTC, KwakEuiJin approved these changes
LGTM🍀 고생하셨습니다. 수정만 하고 머지 부탁드려욥

2023-07-15 06:56 UTC, KwakEuiJin commented on app/src/main/res/layout/fragment_mypage.xml
> +        android:layout_marginTop="66dp"
dimentionRatio 도 활용하면 좋을 것 같네욥

2023-07-15 06:56 UTC, KwakEuiJin commented on app/src/main/res/layout/fragment_mypage.xml
> +            app:layout_constraintTop_toTopOf="@id/tv_mypage_story_title" />
이미지뷰는 왠만하면 고정 크기를 잡아주는게 좋아욥!! 디자이너측에서 잘못 전달할리는 없지만 간혹 서버 이미지로 변경될때 크기 변경이 일어나며 뷰가 깨집니당

2023-07-15 06:56 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +                //TODO Intent to Story
👍

2023-07-15 08:00 UTC, l2hyunwoo requested changes
색상값만 잘 수정하면 머지 바로 가능할 듯

2023-07-15 08:00 UTC, l2hyunwoo commented on app/src/main/res/layout/fragment_mypage.xml
> +        app:layout_constraintHorizontal_bias="0.0"
이 친구 강제로 넣은건가요?

2023-07-15 14:39 UTC, librarywon commented on app/src/main/res/layout/fragment_mypage.xml
> +        android:layout_marginTop="66dp"
넵 그게 좋을 것 같네요 반영하겠습니다!

2023-07-15 14:41 UTC, librarywon commented on app/src/main/res/layout/fragment_mypage.xml
> +            app:layout_constraintTop_toTopOf="@id/tv_mypage_story_title" />
아 그럴수가 있군요 고정크기를 잡아서 반영하겠습니다 ㅎㅎ

2023-07-15 14:41 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +            //setting 이동
넵!

2023-07-15 14:41 UTC, librarywon commented on app/src/main/res/drawable/bg_round_16dp_gray20.xml
> +    <solid android:color="@color/gray_20"/>
반영하겠습니다!

2023-07-15 14:56 UTC, librarywon commented on app/src/main/res/layout/fragment_mypage.xml
> +        app:layout_constraintHorizontal_bias="0.0"
자동으로 추가된 부분 같습니다 삭제하겠습니다!

2023-07-15 14:56 UTC, librarywon commented on app/src/main/res/layout/fragment_mypage.xml
> +            android:layout_height="103dp"
해결해보겠습니다!

2023-07-15 14:56 UTC, librarywon commented on app/src/main/res/layout/fragment_mypage.xml
> +        android:background="#EBE8FF"
일러스트가 들어올 영역을 잡아둔 친구라서 일러스트가 들어오면 삭제 예정입니다!

2023-07-17 17:03 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +                        toast(myPageInfoState.data.toString())
넵 삭제하였습니다!

2023-07-17 17:12 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/data/network/model/mypage/MyPageResponse.kt
> +        return Profile(id,realName, nickname, profileImageUrl,photoCount)
lint!

2023-07-17 17:12 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +                //TODO Intent to Story
이거 먼저 머지하고 공유하기를 나중에 올려야하겠네

2023-07-17 17:13 UTC, l2hyunwoo approved these changes
👍🏻

2023-07-18 16:56 UTC, merged