[Feature/album viewpager]: AlbumCover 수정 화면 작업
TeamPophory/pophory-android pull request #159
Opened 2023-07-14 07:45 UTC by KwakEuiJin

## 이슈 코드 

- close #148 

## 📸 스크린샷

https://github.com/TeamPophory/pophory-android/assets/93872496/f4972118-86ea-46d0-83e0-76aa7122c059

2023-07-14 12:17 UTC, librarywon commented
테마당 커버가 여러개라서 지금 구현한 뷰가 기획과 조금 차이가 있는것 같습니다

2023-07-14 12:22 UTC, librarywon approved these changes
LGTM ✨

2023-07-14 12:22 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditViewModel.kt
> +        )
앨범이 테마별로 여러개로 늘어나면 2차원 리스트로 가야겠네요!

2023-07-14 12:22 UTC, librarywon commented on app/src/main/res/layout/fragment_store.xml
> +
제가 작업하는 부분이랑 겹치는데 충돌이 조금 우려됩니당

2023-07-14 12:25 UTC, librarywon requested changes
어프로브를 잘못날렸네요 😢

2023-07-14 13:39 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditViewModel.kt
> +        )
AlbumCoverItem 얘가 있어서 2차 리스트는 필요 없을 것 같습니다!

2023-07-14 13:39 UTC, KwakEuiJin commented on app/src/main/res/layout/fragment_store.xml
> +
먼저 머지하시면 충돌 관리하겠읍니다.

2023-07-19 18:16 UTC, librarywon reviewed
LGTM ✨

2023-07-19 23:49 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditActivity.kt
> +        (binding.vpAlbumCover.adapter as? AlbumCoverEditAdapter)?.submitList(viewModel.getAlbumItemList())
굳굳임다!

2023-07-19 23:49 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/cover/model/AlbumCoverItem.kt
> +    }
ENUM 사랑해요

2023-07-20 00:24 UTC, l2hyunwoo requested changes
리뷰 확인해주세영

2023-07-20 00:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditActivity.kt
> +    }
```suggestion
    private val binding by viewBinding(ActivityAlbumCoverEditBinding::inflate)
```

2023-07-20 00:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditActivity.kt
> +            viewModel.patchAlbumCover(albumId, )
```suggestion
            viewModel.patchAlbumCover(albumId)
```

뒤에 뭐 더 들어가야할 param있어?

2023-07-20 00:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/cover/model/AlbumCoverItem.kt
> +    val imageRes: Int,
```suggestion
    @DrawableRes val imageRes: Int,
```

이렇게 적어도 되지 않을까유?

2023-07-20 00:26 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditActivity.kt
> +            viewModel.patchAlbumCover(albumId, )
내 마음..
삭제하겠읍니다

2023-07-20 00:36 UTC, l2hyunwoo approved these changes

2023-07-20 03:43 UTC, librarywon approved these changes
고생했쏘

2023-07-20 03:43 UTC, merged