[Feature/store] 내 서랍(store) 2차 스프린트 기능구현
TeamPophory/pophory-android pull request #160
Opened 2023-07-14 09:26 UTC by librarywon

## 이슈 코드 

- close #145 
- close #177 

## 📸 스크린샷
<img width="393" alt="스크린샷 2023-07-14 오후 6 21 18" src="https://github.com/TeamPophory/pophory-android/assets/52442547/9fe8bcfd-bc7f-4f56-ad82-cef47ff6cfab">

## 🍀 관련 이슈
- progress bar는 저 포릿 아이콘을 사용할 수 없어 seekBar에서 터치를 비활성화하고 커스텀하였습니다.
- 15장 모두 사진이 찼을 때 아이콘이 자동으로 변경되게 로직을 작성하였습니다.
- setSpannableString() 함수를 범용성 있게 조금 개선하였습니다.

2023-07-15 07:54 UTC, l2hyunwoo requested changes
고생하셨습니다.

2023-07-15 07:54 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +            }
여기 아직 미구현상태면 pr draft 걸어놓는게 좋을 것 같아요

2023-07-15 07:54 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +            seekBarStore.setOnTouchListener { _, _ -> true }
이런 방식말고 혹시 touch 막는 다른 속성이 존재하지 않니?

2023-07-15 07:54 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +                    val maxPhoto = 15
maxPhoto는 클라보다 서버에서 관리하는게 좋지 않을까 하는 생각이 듭니다. @unanchoi

2023-07-15 07:54 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +        val coloredText = "포포리 앨범"
포포리 앨범 const val로 빼자

2023-07-15 12:16 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +            seekBarStore.setOnTouchListener { _, _ -> true }
비활성화시키면 그 테마 적용되서 다른색이 될 수도 있다고 하더라구요!

2023-07-15 12:16 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +                    val maxPhoto = 15
네 그 방식의 논의가 필요합니다

2023-07-15 12:17 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +        val coloredText = "포포리 앨범"
넵!

2023-07-15 12:26 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +            seekBarStore.setOnTouchListener { _, _ -> true }
아하 좋습니다.

2023-07-15 14:36 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +            }
의진이 파트를 합쳐야 하는거라 TODO를 써두었습니다!

2023-07-17 18:02 UTC, l2hyunwoo approved these changes

2023-07-17 18:25 UTC, librarywon commented
@KwakEuiJin  store의 AlbumItem data class의 id의 자료형을 long으로 변경하니, 의진님이 작성하신 photo에 관련된 albumId들도 변경해야하는 이슈가 생겼니다.
photo에 albumId들을 전부 Long으로 변경하고 이슈를 해결하였습니다.

2023-07-18 17:08 UTC, merged