[Feature/share] 공유하기 화면 제작완료
TeamPophory/pophory-android pull request #172
Opened 2023-07-17 09:28 UTC by librarywon

## 이슈 코드 

- close #150 

## 📸 스크린샷
<img width="393" alt="스크린샷 2023-07-17 오후 6 25 51" src="https://github.com/TeamPophory/pophory-android/assets/52442547/6cf826f7-3db7-4409-9cc5-439207d69093">

## 🍀 관련 이슈
- 공유하기 화면 V2 api가 아직 나오지 않아서 앨범 내 사진 조회 api를 사용하였습니다.

2023-07-17 12:36 UTC, l2hyunwoo requested changes
고생했습니다

2023-07-17 12:36 UTC, l2hyunwoo commented on app/build.gradle.kts
> +    alias(libs.plugins.kotlin.android)
이미 적용되어있습니당

2023-07-17 12:36 UTC, l2hyunwoo commented on app/build.gradle.kts
> +    implementation(libs.material)
요것도

2023-07-17 12:36 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/share/model/PhotoItem.kt
> +    val id: Int,
Long 타입 아닐까요?

2023-07-17 13:39 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/share/model/PhotoItem.kt
> +    val id: Int,
네 맞습니다!

2023-07-18 05:32 UTC, KwakEuiJin requested changes
리뷰 확인 부탁드립니다.

2023-07-18 05:32 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +
요거 뷰모델에서 관리해도 좋을 것 같아요

2023-07-18 05:32 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +                    viewModel.getPhotos()
요거 init 블럭으러 옮겨도 좋을 것 같습니당

2023-07-18 05:32 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +    }
해당 함수 분리 부탁드려요

2023-07-18 05:32 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/share/adapter/ShareAdapter.kt
> +        onShareSheetDismissed()
binding에 직접 접근하기보다 리스너를 전달하는 방식이 좋아보입니다.

2023-07-18 20:24 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +    }
넵 분리하겠습니다!

2023-07-18 20:25 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +                    viewModel.getPhotos()
viewModel.getPhotos()를 init으로 옮기면 좋은 이유를 말씀해주실 수 있을까요?

2023-07-18 20:25 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +
저도 그렇게 생각합니다 반영하겠습니다!

2023-07-18 20:34 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/share/adapter/ShareAdapter.kt
> +        onShareSheetDismissed()
넵 해보겠습니다!

2023-07-19 01:37 UTC, l2hyunwoo reviewed
onViewRecycled 콜백은 왜 사용했는지만 설명해주시면 될 것 같습니당.

2023-07-19 01:37 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +    private var shareAdapter: ShareAdapter? = null
Activity 단에선 굳이 이러지 않아도 될 것 같아

2023-07-19 01:37 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +                    viewModel.getPhotos()
observe는 conifg change에 따라서 N번 호출될 수 있는데 init은 확정적으로 한번만 호출 됨

2023-07-19 01:37 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +        startForResult.launch(Intent.createChooser(shareIntent, "외부 공유하기"))
흐...이거 데이터 넣어주는건 내가 할게

2023-07-19 01:37 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/share/adapter/ShareAdapter.kt
> +    }
이걸 활용한 이유가 있나유?

2023-07-19 01:51 UTC, KwakEuiJin requested changes
코드리뷰 부탁드립니다~!! 고생하셨어요

2023-07-19 01:51 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +        setOnClickListener()
얘네는 왜  observe내의 초기화시에 들어가 있지 않은가요?

2023-07-19 01:51 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/share/adapter/ShareAdapter.kt
> +            }
여기서 position을 뱉어내기보다 PhotoItem의 식별 가능 변수를 활용하여 Adapter의 currentList에서 position을 유추하는 것이 좋은 구조라고 생각됩니다

2023-07-19 01:51 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +                }
요기 ViewHolder의 binding에 직접 접근하기보다 이벤트를 통해 처리하는 것이 좋아보입니다.

2023-07-19 01:51 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/share/adapter/ShareAdapter.kt
> +        val binding: ItemSharePhotoBinding,
binding은 private로 선언해주세요

2023-07-19 07:35 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +    private var shareAdapter: ShareAdapter? = null
넵 반영하겠습니다!

2023-07-19 07:35 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +        startForResult.launch(Intent.createChooser(shareIntent, "외부 공유하기"))
넵 TODO로 남겨두겠습니다!

2023-07-19 08:53 UTC, l2hyunwoo approved these changes

2023-07-19 10:24 UTC, KwakEuiJin approved these changes

2023-07-19 10:28 UTC, merged