[feature/share-image] 사진 공유 기능 추가
TeamPophory/pophory-android pull request #179
Opened 2023-07-18 03:10 UTC by l2hyunwoo

## 이슈 코드 

- close #178

2023-07-19 18:23 UTC, librarywon approved these changes
LGTM ✨

2023-07-19 18:23 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +            }
소중한 다이나믹 링크 코드 열심히 보겠습니다!

2023-07-19 18:23 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveImageViewModel.kt
> +
공백이 있습니다!

2023-07-19 18:23 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveSharedImageActivity.kt
> +        lifecycleScope.launch {
기능들을 혹시 함수로 따로 분리하지 않으신 이유가 있을까요?!

2023-07-20 00:01 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveSharedImageActivity.kt
> +        lifecycleScope.launch {
간단한 로직만 있어서 (버튼클릭, 사진 정보 받아오기) 굳이 추가 분리하지 않아도 된다고 생각했습니다.

2023-07-20 00:15 UTC, KwakEuiJin requested changes
LGTM

2023-07-20 00:15 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/share/ShareActivity.kt
> +
👍

2023-07-20 00:15 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveImageViewModel.kt
> +    data class Photo(
❤️

2023-07-20 00:15 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveImageViewModel.kt
> +                authorizedService.acceptShare(photoState.photoId)
loading 추가 PLZ🙏

2023-07-20 00:15 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveSharedImageActivity.kt
> +                    }
👍 백스택 쌓이는 부분 잘배우고 가요!!

2023-07-20 00:17 UTC, KwakEuiJin approved these changes
LGTM 🎉
어려운 기능 고생 많으셨습니다.

2023-07-20 00:20 UTC, merged