[feature/ui_test]: UiTestSample 추가
TeamPophory/pophory-android pull request #234
Opened 2023-08-01 14:29 UTC by KwakEuiJin

## 이슈 코드 

- close #233

2023-08-01 15:22 UTC, l2hyunwoo requested changes
제가 손 좀 보겠습니다.

2023-08-01 15:22 UTC, l2hyunwoo commented on app/build.gradle.kts
> +    androidTestImplementation (libs.androidx.test.truth)
lint 그리고 웬만한건 전부 bundle로 묶을 수 있을 듯

2023-08-01 15:22 UTC, l2hyunwoo commented on build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/AndroidTestPlugin.kt
> +            "testImplementation"(libs.findLibrary("espresso").get())
androidTestImplementation?

2023-08-01 23:51 UTC, KwakEuiJin commented on app/build.gradle.kts
> +    androidTestImplementation (libs.androidx.test.truth)
haha thank you

2023-08-01 23:51 UTC, KwakEuiJin commented on build-logic/convention/src/main/kotlin/com/teampophory/pophory/plugin/AndroidTestPlugin.kt
> +            "testImplementation"(libs.findLibrary("espresso").get())
yes good code

2023-08-01 23:53 UTC, KwakEuiJin commented
I want give approve to you, this Ui Sample is nice 🔫

2023-08-02 01:44 UTC, l2hyunwoo approved these changes

2023-08-02 01:45 UTC, merged