Feature/share module
TeamPophory/pophory-android pull request #252
Opened 2023-08-18 12:32 UTC by KwakEuiJin

## 이슈 코드 
- close #250 

feature 멀티모듈 분리가 처음이다보니 커밋을 한번에 때려버렸습니다..ㅎㅎ
dependency 잘 추가한건지 한번 확인해주세요~~!!

2023-08-18 14:01 UTC, l2hyunwoo requested changes
리뷰 확인해주세요!

2023-08-18 14:01 UTC, l2hyunwoo commented on feature/share/build.gradle.kts
> +    }
내가 데이터 바인딩을 포함시키긴 했는데 안쓰이면 viewBinding으로 바꿔줘!

2023-08-18 14:01 UTC, l2hyunwoo commented on feature/share/build.gradle.kts
> +    implementation(libs.bundles.firebase)
파이어베이스도 쓰이니?

2023-08-18 14:01 UTC, l2hyunwoo commented on feature/share/proguard-rules.pro
삭제!

2023-08-18 14:01 UTC, l2hyunwoo commented on feature/share/src/androidTest/java/com/teampophory/pophory/feature/share/ExampleInstrumentedTest.kt
삭제

2023-08-18 14:01 UTC, l2hyunwoo commented on feature/share/src/test/java/com/teampophory/pophory/feature/share/ExampleUnitTest.kt
안쓰이면 삭제

2023-08-19 06:05 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/data/network/model/share/SharePhotoResponse.kt
> +fun SharePhotoResponse.toSharePhoto() = SharePhoto(
이게 어떤 뜻인지 잘 이해가 안감!

2023-08-19 06:05 UTC, KwakEuiJin commented on app/build.gradle.kts
> +    implementation(projects.domain.share)
아 데이터 모듈 깜빡했다.. 으아아아아아아

2023-08-19 06:09 UTC, KwakEuiJin commented on domain/share/src/androidTest/java/com/teampophory/pophory/domain/share/ExampleInstrumentedTest.kt
도메인은 테스트 코드를 쓸 일 많지 않을까??

2023-08-19 06:12 UTC, KwakEuiJin commented on feature/share/build.gradle.kts
> +    implementation(libs.bundles.firebase)
다이나믹링크 쓰는중!

2023-08-19 06:13 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/data/network/model/share/ShareResponse.kt
> +    val photoDetails: List<PhotoDetail>
domain에 포토와 이름이 겹쳐서 ㅎ..ㅎ

2023-08-19 06:13 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/data/repository/share/DefaultShareRepository.kt
> +    private val shareNetworkDataSource: ShareNetworkDataSource,
넵! 분리하겠습니다

2023-08-19 06:14 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/data/network/model/share/AcceptShareResponse.kt
> +)
흠 근데 domain entity 이름 정의시에 data의 dto name에서 Response를 빼는게 맞다고 논의했었지 않았나??!!

2023-08-19 06:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/data/network/model/share/AcceptShareResponse.kt
> +)
도메인 이름 자체가 이상하다는거였음...

2023-08-19 06:25 UTC, l2hyunwoo commented on domain/share/src/androidTest/java/com/teampophory/pophory/domain/share/ExampleInstrumentedTest.kt
그런데 당장은 쓰지 않고 있고 domain 모듈에서 InstrumentedTest가 있는건 맞지 않은 것 같아

2023-08-19 06:36 UTC, KwakEuiJin commented on domain/share/src/androidTest/java/com/teampophory/pophory/domain/share/ExampleInstrumentedTest.kt
오케잇! 삭제 ㄱㄱ

2023-08-19 14:54 UTC, l2hyunwoo requested changes
리뷰확인 더 부탁! 그리고 네이밍 쪽은 PR 한 개 더 만들어보자...!!

+) 이건 이번 QA 스프린트 때 머지하지 말고 3차 스프린트 도중에 한번 더 출시 나가자

2023-08-19 14:54 UTC, l2hyunwoo commented on data/share/src/main/java/com/teampophory/pophory/data/share/repository/DefaultShareRepository.kt
> +    @Unsecured private val provideUnsecuredShareService: ShareService
```suggestion
    @Secured private val shareService: ShareService,
    @Unsecured private val unsecuredShareService: ShareService
```

2023-08-19 14:54 UTC, l2hyunwoo commented on feature/share/build.gradle.kts
> +    implementation(libs.bundles.retrofit)
여기서 bundles retrofit이 필요한가?

2023-08-19 14:54 UTC, l2hyunwoo commented on feature/share/build.gradle.kts
> +    implementation(projects.core.network)
여기서 core.network 모듈이 참조되어야 하는 이유가 있을까?

2023-08-19 14:54 UTC, l2hyunwoo commented on feature/share/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveImageViewModel.kt
> +    data class AcceptedSharPhotoData(
모든 데이터 클래스(혹은 클래스)는 데이터를 표현하는 클래스인데 suffix에 Data 붙이는 건 불필요한 말을 덧붙이는 것 같아

2023-08-19 14:54 UTC, l2hyunwoo commented on feature/share/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveImageViewModel.kt
> +    data class AcceptedSharPhotoData(
그리고 오타남 Shar -> Share

2023-08-20 12:22 UTC, KwakEuiJin commented on feature/share/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveImageViewModel.kt
> +    data class AcceptedSharPhotoData(
오타... 수정하겠습니다!

2023-08-22 09:21 UTC, KwakEuiJin commented on feature/share/src/main/java/com/teampophory/pophory/feature/share/receive/ReceiveImageViewModel.kt
> +    data class AcceptedSharPhotoData(
오늘내로 수정해서 푸시하겠습니다~!!!

2023-08-22 12:42 UTC, KwakEuiJin commented on feature/share/build.gradle.kts
> +    implementation(projects.core.network)
PophoryDataStore 요 아이땜에 필요합니다!

2023-08-22 13:08 UTC, l2hyunwoo commented on feature/share/build.gradle.kts
> +    implementation(projects.core.network)
화긴

2023-08-30 12:43 UTC, l2hyunwoo approved these changes
머지갑시다 🚀

2023-08-31 08:12 UTC, merged