[Feature/admob_reward_video]: 리워드 비디오 광고 작업
TeamPophory/pophory-android pull request #311
Opened 2023-10-16 13:01 UTC by KwakEuiJin

## 이슈 코드 

- close #310 

## 🍀 관련 이슈
현재 버전인 1.1.4 에서 광고 리스트가 내려오지 않는 이슈가 있어서 테스트는 아직 해보지 못했습니다.

2023-10-16 14:59 UTC, l2hyunwoo requested changes

2023-10-16 14:59 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditActivity.kt
> +        ).apply {
생성자 오버로딩?

2023-10-16 14:59 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +    }
```suggestion
    private fun moveToAlbumCoverEditActivity() {
        if (viewModel.albums.value !is StoreState.SuccessAlbums) {
            return
        }
        val currentAlbumPosition = homeViewModel.homeState.value.currentAlbumPosition
        val albumItem = viewModel.getCurrentAlbumItem(currentAlbumPosition)
        val currentAlbumCoverId = albumItem?.albumCover ?: 1
        val intent = AlbumCoverEditActivity.newIntent(
            context = requireContext(),
            albumCoverId = currentAlbumCoverId,
            albumId = albumItem?.id ?: 0
        )
        albumCoverChangeLauncher.launch(intent)
}
```

2023-10-16 14:59 UTC, l2hyunwoo commented on domain/ad/proguard-rules.pro
삭제

2023-10-16 14:59 UTC, l2hyunwoo commented on domain/ad/src/main/java/com/teampophory/pophory/ad/entity/AdConstant.kt
> +    val adName: String
```suggestion
    val id: String,
    val name: String
```

2023-10-17 11:14 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/HomeViewModel.kt
> +    private val saveAdConstantUseCase: GetAdConstantUseCase
헿

2023-10-17 11:14 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditActivity.kt
> +        ).apply {
구두로 얘기했던 것처럼 함수로 생성중이여서 그냥 유지할게요!

2023-10-17 11:15 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/config/ad/AdmobRewardedAdService.kt
> +
이거 쩝니다 👍

2023-10-17 11:15 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditActivity.kt
> +            val adConstant = viewModel.getAdConstant(AdName.ALBUM_EDIT_COVER_REWARD_01.adName)
이름땜에 헷갈린듯 수정해놓을게요!

2023-10-17 11:19 UTC, KwakEuiJin commented on domain/ad/src/main/java/com/teampophory/pophory/ad/entity/AdConstant.kt
> +    val adName: String
수정 완료!

2023-10-17 11:38 UTC, l2hyunwoo approved these changes

2023-10-17 11:38 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/config/ad/AdmobRewardedAdService.kt
👍🏻

2023-10-17 11:38 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/cover/AlbumCoverEditActivity.kt
> +        ).apply {
ㅇㅋ

2023-10-17 11:38 UTC, l2hyunwoo commented on domain/ad/src/main/java/com/teampophory/pophory/ad/entity/AdIdentifier.kt
> +)
👍🏻

2023-10-17 11:38 UTC, l2hyunwoo commented on data/ad/src/main/java/com/teampophory/pophory/ad/model/AdConstantResponse.kt
> +    name = adName ?: ""
```suggestion
    id = adId.orEmpty(),
    name = adName.orEmpty()
```

2023-10-17 11:38 UTC, l2hyunwoo commented on data/ad/src/main/java/com/teampophory/pophory/ad/model/AdConstantResponse.kt
> +fun AdConstantResponse.toAdConstant() = AdIdentifier(
```suggestion
fun AdConstantResponse.toAdIdentifier() = AdIdentifier(
```

2023-10-17 12:51 UTC, librarywon reviewed
의진이 수고했서 시험끝나고 더 자세히 볼 수 있어서 그 때 물어볼게오

2023-10-17 14:42 UTC, merged