Feature/qr
TeamPophory/pophory-android pull request #314
Opened 2023-10-17 10:42 UTC by librarywon

## 이슈 코드 

- close #292 

## 📸 스크린샷
구현 사진은 카카오톡방에 보내드리고 추후 더 업데이트하겠습니다.

## 🍀 관련 이슈
- 웹사이트 내부에 사진이 있는 사진관들은 대부분 대응이 가능합니다.
- 버튼로만 다운받는 사진관은 지원하지 않습니다.
- 현재 확인해본 사진관으로는 (인ㅇ네컷, 포ㅇ시그니처,하ㅇ필름)이 돌아가는 것을 확인하였습니다.

2023-10-17 11:02 UTC, l2hyunwoo requested changes
로직 상당히 어려웠을텐데 고생많으셨습니다 👍🏻 한번 리뷰 확인해주세요

2023-10-17 11:02 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/qr/QRActivity.kt
> +        })();"""
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋinjectJS까지 했네...고생했다

그리고 var 말고 const로 해줄 수 있나?

2023-10-17 11:02 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/qr/QRActivity.kt
> +                    }
```suggestion
                    viewModel.uiState.value = if (uri != null) {
                        QRState.Success(uri)
                    } else {
                        QRState.Fail(getString(R.string.qr_image_download_fail))
                    }
```

2023-10-17 11:07 UTC, librarywon commented on app/src/main/AndroidManifest.xml
> +            android:name=".onboarding.OnBoardingActivity"
다시 com.teampophory.pophory로 반영하겠습니다!

2023-10-17 11:08 UTC, librarywon commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
예전에 사용해본 기억으로 당연히 사용하는줄 알았는데 몰랐습니다! 하위버전 대응이 가능하다니 이거는 그냥 두고 알고 있겠습니다!

2023-10-17 11:09 UTC, librarywon commented on app/build.gradle.kts
> +    implementation(libs.material)
삭제!!

2023-10-17 11:09 UTC, librarywon commented on app/build.gradle.kts
> +    alias(libs.plugins.kotlin.android)
삭제!!

2023-10-17 11:11 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/qr/QRActivity.kt
> +        binding.toolbarQr.txtToolbarTitle.text = getText(R.string.qr_toolbar_text)
getText구현 함수가 context코어에 있었군요 감사합니다!

2023-10-17 11:13 UTC, KwakEuiJin reviewed
고생 많으셨습니다~!! 👏

2023-10-17 11:13 UTC, KwakEuiJin commented on app/src/main/AndroidManifest.xml
> +            android:exported="true" />
exported false !

2023-10-17 11:13 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/add/AddPhotoBottomSheet.kt
> +                addPhotoResultLauncher.launch(intent)
onAttach에서 초기화 하는 이유가 따로 있나요?!

2023-10-17 11:13 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/qr/ImageDownloader.kt
> +}
unRegisterReceiver 는 어디서 하고있는지 확인해주셔야할 것 같아요

2023-10-17 11:13 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/qr/ImageDownloader.kt
> +}
없다면 추가 부탁드립니다~!!

2023-10-17 11:13 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/qr/QRActivity.kt
> +                is QRState.Loading -> {}
core에 있숩니다

2023-10-17 11:16 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/qr/QRActivity.kt
> +        }
이게 decorateBarcodeView 내부의 viewfinder(바코드 인식하는 네모부분)의 위치를 framingRect라는 애가 알고 있어서 가져오고,
decorateBarcodeView의 viewfinder의 statusTextView(바코드에 나오는 텍스트)의 위치를 viewfinder바로 아래 위치 시키는겁니다!

처음에 그릴때 바로 위치를 잡아주려고 했으나 viewfinder가 그려지기 전에 statusTextView가 먼저 자리를 잡아서 위치를 잡지 못하였고 다 그려진 후에 위치를 잡아주기위해 addOnLayoutChangeListener함수를 사용했습니다.

다른 방법를 선택하는 것이 저도 좋을 듯 싶은데 아직 방법을 잘 모르겠습니다. ㅠㅠ

2023-10-17 11:17 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/qr/QRActivity.kt
> +        })();"""
넵!!

2023-10-17 11:19 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/qr/QRActivity.kt
> +                    }
더 코틀린스럽고 좋은것 같습니당 ㅎㅎ

2023-10-17 11:19 UTC, librarywon commented on app/src/main/AndroidManifest.xml
> +            android:exported="true" />
앗 걸렸다!

2023-10-17 11:20 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/qr/QRActivity.kt
> +}
js 코드입니다..

2023-10-17 11:23 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/qr/QRActivity.kt
> +    }
기존에 분리되어있던 변수를 함수화 하는과정에 지우지 않았던거 같네요 감사합니다!!

2023-10-17 11:26 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/qr/QRActivity.kt
> +    }
아 올바른 url만 넘어올거라고 생각한 나...

2023-10-17 11:27 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/qr/ImageDownloader.kt
> +}
unRegisterReceiver가 없습니다 추가하겠습니다!

2023-10-17 11:38 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/add/AddPhotoBottomSheet.kt
> +                addPhotoResultLauncher.launch(intent)
`registerForActivityResult` 속에서 context를 사용하고 있는데 context가 프레그먼트에 가장 먼저 연결되는 시점인 `onAttach`에서 초기화해야 문제가 없을 것 같아서 onAttach에서 진행했습니다

2023-10-17 12:47 UTC, l2hyunwoo approved these changes
Merge it

2023-10-17 12:49 UTC, merged

2023-10-18 14:22 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/qr/QRActivity.kt
> +        })();"""
@joonBaek12 이거 로직