Feature/flexbox
TeamPophory/pophory-android pull request #49
Opened 2023-07-01 16:58 UTC by KwakEuiJin

## 이슈 코드 
close #31 

## 📸 스크린샷
<img width="281" alt="KakaoTalk_Photo_2023-07-02-01-56-33" src="https://github.com/TeamPophory/pophory-android/assets/93872496/e980ad14-3155-4925-8ace-ebb4316e5a27">

## 🍀 관련 이슈
- 지금은 리소스 크기가 정해져있어서 가능한 기능인데요 서버측에서 내려받을 때 각 dp값으로 대응하다보면 기기별로 사진 정렬에서 문제가 될 수도 있을 것 같습니다. 
- 즉 GridLayoutManager로 기능 변경될 가능성이 큽니다.

2023-07-01 17:20 UTC, librarywon approved these changes
LGTM ✨ 고생하셨습니당

2023-07-01 17:20 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/album/AlbumListActivity.kt
> +    }
```kt
 private var binding: ActivityAlbumListBinding
 binding = ActivityAlbumListBinding.inflate(layoutInflater)
```
이게 한 번에 처리 된 코드가 맞을까요?

2023-07-01 17:20 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/album/viewholder/FlexBoxLayoutViewHolder.kt
> +class FlexBoxLayoutViewHolder(
ViewHolder를 어뎁터에 넣지 않고 분리하는 이유는 유지 보수 용이하기 때문일까요?

2023-07-01 17:29 UTC, l2hyunwoo requested changes
굳 리뷰 확인 부탁드려요

2023-07-01 17:29 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/AlbumListActivity.kt
> +    }
```suggestion
    private val binding by viewBinding(ActivityAlbumListBinding::inflate)
```

util쪽 함수 사용하는 방향으로 가볼까요?

2023-07-01 17:29 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/viewholder/FlexBoxLayoutViewHolder.kt
> +class FlexBoxLayoutViewHolder(
이건 개인취향일수도...?

2023-07-01 17:29 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/viewholder/FlexBoxLayoutViewHolder.kt
> +    fun bind(id: Int) {
```suggestion
    fun bind(@DrawableRes id: Int) {
```

이정도 처리

2023-07-01 18:28 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/AlbumListActivity.kt
> +    }
늦은 초기화를 사용하여 binding 참조시에 init하는 것이 by lazy입니당

2023-07-01 18:30 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/AlbumListActivity.kt
> +    }
음 조금 다른개념입니다. binding을 호출 시에 정의된 구문의 초기화 로직을 진행한다고 생각하시면 될 것 같습니다.

2023-07-01 18:33 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/viewholder/FlexBoxLayoutViewHolder.kt
> +class FlexBoxLayoutViewHolder(
갠취이기도 하고 애초에 관심사를 아예 분리하고자 함에 있습니다. Adapter 내에 ViewHolder를 참조시 간혹 inner class를 사용하여 메모리 누수가 발생될 수 도 있습니다. 그걸 아예 방지하고자 하는 목적도 있어요

2023-07-01 18:33 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/AlbumListActivity.kt
> +    }
넹 좋습니다

2023-07-01 18:34 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/viewholder/FlexBoxLayoutViewHolder.kt
> +    fun bind(id: Int) {
좋아욥!

2023-07-02 01:37 UTC, l2hyunwoo reviewed
코멘트 반영해주시면 감사하겠습니다.

2023-07-02 01:37 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/AlbumListViewModel.kt
> +}
이거 나중에 서버통신 연결하면 로직 다 뜯어 고쳐야되니까 미리 Data Layer - UI Layer 분리 시킨 다음에 Data Layer에서 리스트 넘겨주는 쪽으로 구현하면 서버통신 연결할 때 시간 많이 줄어들 것 같아.

2023-07-02 02:40 UTC, l2hyunwoo reviewed
리뷰 봐주세요

2023-07-02 02:40 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/HomeActivity.kt
> +import android.content.Intent
이거 왜 추가되었나요?

2023-07-02 02:40 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/AlbumListViewModel.kt
> +    val albumList: LiveData<PhotoListResponse> get() = _albumList
Response에서 UiModel로 한번 끊자

2023-07-02 02:43 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/HomeActivity.kt
> +import android.content.Intent
ㅋㅋㅋ.. test 하다가 삭제하고 푸시할게요

2023-07-02 02:43 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/AlbumListViewModel.kt
> +    val albumList: LiveData<PhotoListResponse> get() = _albumList
오케이!!

2023-07-02 02:54 UTC, l2hyunwoo approved these changes
리뷰 확인하고 수정하거나 아님 걍 머지 ㄱ

2023-07-02 02:54 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/model/PhotoList.kt
> +data class PhotoList(
PhotoUiState?

https://developer.android.com/topic/architecture/ui-layer

2023-07-02 03:06 UTC, l2hyunwoo approved these changes

2023-07-02 03:10 UTC, merged