[feat/onBoarding] : 스플래시와 온보딩 뷰 구현
TeamPophory/pophory-android pull request #50
Opened 2023-07-01 17:00 UTC by jihyeonAnAn

## 이슈 코드 

- close #47 

## 📸 스크린샷

https://github.com/TeamPophory/pophory-android/assets/84323575/1aed0b80-b3d0-43ab-a48a-a33dff6387bf

## 🍀 관련 이슈

- 아직 폰트와 컬러 적용 되지 않음

2023-07-01 17:06 UTC, KwakEuiJin requested changes
안드 개발 가보자잇

2023-07-01 17:06 UTC, KwakEuiJin commented on app/src/main/AndroidManifest.xml
> +            android:exported="true"/>
여기선 exported가 true일 이유는 없어보입니다!
```suggestion
        <activity
            android:name=".OnBoardingActivity"
            android:exported="false"/>
```

2023-07-01 17:06 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/OnBoardingActivity.kt
> +            )
요거 Color Resource로 빼주시면 좋을 것 같습니다.

2023-07-01 17:06 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/OnBoardingViewPagerAdapter.kt
> +
ViewExt.kt 파일의 ItemDiffCallback을 활용하시면 될 것 같습니다.

2023-07-01 17:11 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/OnBoardingActivity.kt
> +        }
attachTo 라는 애로 연결시켜서 쓰는 방법이 알맞은 방법인 것 같습니다.
```
    val adapter = ViewPagerAdapter()
    viewPager.adapter = adapter
    dotsIndicator.attachTo(viewPager)
```

2023-07-01 17:27 UTC, l2hyunwoo requested changes

2023-07-01 17:27 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/OnBoardingActivity.kt
> +            }
```suggestion
            when(position) {
                binding.dotIndicatorFirst.isSelected = position == 0
                binding.dotIndicatorSecond.isSelected = position == 1
                binding.dotIndicatorThird.isSelected = position == 2
            }
```

이런식으로 줄일 수도 있을 것 같아요

2023-07-01 17:27 UTC, l2hyunwoo commented on gradle/libs.versions.toml
> +splash-screen = "1.0.0-beta02"
[1.0.1](https://developer.android.com/jetpack/androidx/releases/core) 버전

2023-07-01 17:27 UTC, l2hyunwoo commented on gradle/libs.versions.toml
> +flipper-noop = { module = "com.facebook.flipper:flipper-noop", version.ref = "flipper" }
없애도 됩니당

2023-07-01 17:27 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/OnBoardingData.kt
> +)
Data 대신 UiModel 정도는 어떨까요?

2023-07-01 17:27 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/OnBoardingData.kt
> +)
```suggestion
data class OnBoardingData (
    val image : String
) {
    val background: Drawable
        get() = Color.parseColor(image).toDrawable()
}
```
이정도로 사용하면

```kotlin
binding.iv.background = item.background
```

이렇게 사용할 수 있을 것 같네요?

2023-07-01 17:27 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/OnBoardingViewPagerAdapter.kt
> +        val diffUtil = object : DiffUtil.ItemCallback<OnBoardingData>() {
이건 거의 상수로 사용해서 UPPER_SNAKE로 적는게 좋을 것 같아요
```suggestion
        val DIFF_UTIL = object : DiffUtil.ItemCallback<OnBoardingData>() {
```

2023-07-01 17:27 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/OnBoardingActivity.kt
> +    private lateinit var splashScreen: SplashScreen
따로 사용하는 구석이 없으면 변수 지우셔도 될 것 같아요

2023-07-01 17:38 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/OnBoardingActivity.kt
> +            }
와우..

2023-07-04 12:46 UTC, l2hyunwoo requested changes
고생했어 지현아! 리뷰 참고하고 수정해줘!

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/on_boarding/OnBoardingActivity.kt
> +        splashScreen = installSplashScreen()
splashScreen 변수 따로 사용하지 않으면 지워도 돼!

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/on_boarding/OnBoardingActivity.kt
> +    private lateinit var binding: ActivityOnBoardingBinding
```suggestion
    private val binding by viewBinding(ActivityOnBoardingBinding::inflate)
```

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/on_boarding/OnBoardingActivity.kt
> +        binding = ActivityOnBoardingBinding.inflate(layoutInflater)
그러면 이거 지워도 돼!

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/on_boarding/OnBoardingActivity.kt
> +            startActivity(intent)
이건 내가 만든거 사용하면 됨!

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/on_boarding/OnBoardingData.kt
> +data class OnBoardingData (
```suggestion
data class OnBoardingData(
```

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/on_boarding/adapter/OnBoardingViewPagerAdapter.kt
> +    diffUtil
DiffUtil 변수는 거의 상수처럼 사용해서 UPPER_SNAKE_CASE로 변수명을 적는 편이야

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/sign_up/SignUpActivity.kt
> +    private lateinit var binding : ActivitySignUpBinding
이 친구도

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/sign_up/SignUpActivity.kt
> +            if(position == 2) {
ctrl alt l 한번 눌러줘!

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/sign_up/SignUpActivity.kt
> +            binding.tabThird.isSelected = position == 2
오 굳..!!!

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/sign_up/SignUpActivity.kt
> +            //isUserInputEnabled = false
이거 isUserInputEnabled false 먹여야되지 않을까?

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/sign_up/SignUpDialogFragment.kt
> +    private val binding get() = _binding!!
```suggestion
    private val binding by viewBinding(FragmentSignUpDialogBinding::bind)
```

이렇게 해주고 onCreateView는

```kotlin
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        dialog?.window?.setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT))
        return FragmentSignUpDialogBinding.inflate(inflater, container, false).root
    }
```

이런식으로 작성하기만 하면 onDestroyView null로 해제 안해줘도 돼!

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/sign_up/SignUpFirstFragment.kt
> +        binding.btnDeleteEditText.isGone = true
binding 내 뷰 건드리는 작업은 웬만하면 onViewCreated에서 작업해보자!

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/sign_up/SignUpFirstFragment.kt
> +    override fun onDestroy() {
```suggestion
    override fun onDestroyView() {
```

로 해줘야합니다!

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/sign_up/SignUpFirstFragment.kt
> +            setOnFocusChangeListener { view, b ->
람다의 패러미터를 최대한 가독성 있게 적어줘...!! 그래야 다른 친구들도 볼 때 이게 어떤 기능인지 대충 알 수 있으니까!

```suggestion
            setOnFocusChangeListener { view, hasFocus ->
```

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/sign_up/SignUpFirstFragment.kt
> +            })
```suggestion
            doOnTextChanged {
                    binding.btnDeleteEditText.isGone = count < 1
                    //글자 수 계산
                    binding.tvTextCount.text = "(${s.toString().length}/6)"

                    //에러 메시지 : 현재 한국어만 지원함!
                    val pattern = Pattern.compile(HANGUL_PATTERN)
                    val matcher = pattern.matcher(binding.editTvName.text)
                    if (!matcher.find()) {
                        binding.tvErrorMessage.text = "현재 한국어만 지원하고 있어요."
                        binding.editTvName.setBackgroundResource(R.drawable.bg_sign_up_edit_text_error)
                        binding.tvErrorMessage.isVisible = true
                    } else if (s.toString().length < 2) {
                        binding.tvErrorMessage.text = "2-6글자 이내로 작성해주세요."
                        binding.editTvName.setBackgroundResource(R.drawable.bg_sign_up_edit_text_error)
                        binding.tvErrorMessage.isVisible = true
                    } else {
                        binding.editTvName.setBackgroundResource(R.drawable.bg_sign_up_edit_text_selected)
                        binding.tvErrorMessage.isVisible = false
                    }
            }
```

doOnTextChanged 라는 함수도 있답니다!

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/sign_up/SignUpFirstFragment.kt
> +            })
+) Pattern.compile도 companion object에서 사용하는 것도 좋을 것 같아

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/sign_up/SignUpFirstFragment.kt
> +            "^[ㄱ-ㅎㅏ-ㅣ가-힣]*\$"
```suggestion
        const val HANGUL_PATTERN = "^[ㄱ-ㅎㅏ-ㅣ가-힣]*\$"
```

2023-07-04 12:46 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/sign_up/adapter/SignUpViewPagerAdapter.kt
> +    private val fragments = listOf(SignUpFirstFragment(), SignUpSecondFragment(), SignUpThirdFragment())
[공식문서](https://developer.android.com/reference/androidx/viewpager2/adapter/FragmentStateAdapter#createFragment(int))에서는 createFragment에서 새로운 Fragment를 생성해서 return하라고 되어있어...!!

2023-07-04 16:34 UTC, jihyeonAnAn commented on app/src/main/java/com/teampophory/pophory/OnBoardingActivity.kt
> +        }
이 부분 dotIndicator 말고 ImageView로 넣어줬습니다!

2023-07-04 17:05 UTC, l2hyunwoo approved these changes
다음 PR에 반영하라는거 빼고 두개는 수정해서 다시 푸시해줘. 그리고 머지 ㄱㄱ

2023-07-04 17:05 UTC, l2hyunwoo commented on app/build.gradle.kts
> +    implementation("com.google.android.material:material:1.5.0")
삭제!

2023-07-04 17:05 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/signup/SignUpActivity.kt
> +    private var currentPosition = 0
currentPosition도 ViewModel로 올려놓는게 좋을거야

2023-07-04 17:05 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/signup/SignUpButtonInterface.kt
> +}
```suggestion
fun interface SignUpButtonInterface {
    fun setButtonState(state : Boolean)
}
```

- (다음 PR에 반영) fun interface로 고쳐보고 어떤 점이 다른지 한번 봐
- (다음 PR에 반영) onChangeState로 함수명 바꿔도 좋을듯

2023-07-04 17:18 UTC, KwakEuiJin approved these changes

2023-07-04 17:18 UTC, KwakEuiJin commented
LGTM 🔫

2023-07-04 17:26 UTC, merged