[feature/store] store view viewpager 및 기능 구현
TeamPophory/pophory-android pull request #55
Opened 2023-07-02 17:57 UTC by librarywon

## 이슈 코드 

- close #44

## 📸 스크린샷
![현재 진행상태](https://github.com/TeamPophory/pophory-android/assets/52442547/35ac9c19-43fe-4347-a26b-a9a3c3d3b598)

## 🍀 관련 이슈
진행 상태 공유를 위한 PR (7월 3일 오전 3시 기준)
- 아이템  itemRippleColor가 설정되지 않고 검은색으로 나오는 이슈가 있음
- 앨범의 사진 보관수 background 미설정

2023-07-02 18:09 UTC, l2hyunwoo requested changes

2023-07-02 18:09 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/my_page/MyPageFragment.kt
> +package com.teampophory.pophory.feature.home.my_page
my_page -> mypage

2023-07-02 18:09 UTC, l2hyunwoo commented on app/src/main/res/layout/fragment_store.xml
> +        app:layout_constraintTop_toBottomOf="@id/tv_store_welcome" />
스크롤 안되게 막아둡시다.

2023-07-02 18:09 UTC, l2hyunwoo commented on app/src/main/res/layout/fragment_store.xml
> +        android:textSize="23sp"
24sp....

2023-07-02 18:16 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/my_page/MyPageFragment.kt
> +package com.teampophory.pophory.feature.home.my_page
확인했습니다!

2023-07-02 18:16 UTC, librarywon commented on app/src/main/res/layout/fragment_store.xml
> +        android:textSize="23sp"
하하 디자인 이슈

2023-07-02 18:16 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +        binding.viewpagerStore.isUserInputEnabled = false
@l2hyunwoo 여기서 스크롤 방지를 걸어두었는데 xml에서 처리하는 것이 좋을까요?

2023-07-02 18:27 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +        binding.viewpagerStore.isUserInputEnabled = false
아 여기서 걸어뒀으면 오케이!

2023-07-02 18:27 UTC, l2hyunwoo commented on app/src/main/res/layout/fragment_store.xml
> +        android:textSize="23sp"
아 이거 그냥 23sp로 갑시다

2023-07-02 19:24 UTC, l2hyunwoo requested changes

2023-07-02 19:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +    private lateinit var adapter: StoreAdapter
```suggestion
    private val adapter: StoreAdapter?
        get() = binding.viewpagerStore.adapter as? StoreAdapter?
```

```suggestion
    private var adapter: StoreAdapter? = null
```

2023-07-02 19:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +            requireContext().startActivity(intent)
albumId 같은 것 넘겨주는 방식으로 만들어볼까?

2023-07-02 19:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +        adapter.submitList(viewModel.mockAlbumList)
observe 하는 방식으로!!

2023-07-02 19:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/apdater/StoreAdapter.kt
> +    class StoreDiffCallback : DiffUtil.ItemCallback<Int>() {
```suggestion
    object StoreDiffCallback : DiffUtil.ItemCallback<Int>() {
```

2023-07-02 19:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/apdater/StoreAdapter.kt
> +        fun bind(src: Int) {
```suggestion
        fun bind(@DrawableRes src: Int) {
```

2023-07-02 19:24 UTC, l2hyunwoo commented on app/src/main/res/values/themes.xml
> +        <item name="android:statusBarColor">@color/white</item>
👍🏻

2023-07-02 19:33 UTC, l2hyunwoo requested changes

2023-07-02 19:33 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +        })
```suggestion
        viewModel.photoList.observe(viewLifecycleOwner) { list ->
            adapter?.submitList(list)
        }
```

2023-07-02 19:35 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +    private lateinit var adapter: StoreAdapter
아래 방법을 채택하겠습니다.

2023-07-02 19:35 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +            requireContext().startActivity(intent)
넵 미리 처리하겠습니다!

2023-07-02 19:35 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +        adapter.submitList(viewModel.mockAlbumList)
반영하였습니다!

2023-07-03 01:10 UTC, KwakEuiJin requested changes
고생하셨습니다~!! 리뷰 확인 부탁드려요

2023-07-03 01:10 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +        adapter = StoreAdapter { position ->
37 공백 삭제 하면 좋을 것 같아욤

2023-07-03 01:10 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +        })
옵저버는 다른 함수로 분리하는 것이 좋아보입니다.

2023-07-03 01:10 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreViewModel.kt
> +    }
init에 걸거면 

MutableLiveData<List<Int>>(mockAlbumList) 가 좋아보입니다

2023-07-03 01:10 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/store/apdater/StoreAdapter.kt
> +    }
inner class는 메모리 누수의 위험성이 존재합니다. 중첩클래스로 구현해주세욥

2023-07-03 01:10 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreViewModel.kt
> +
val photoList: LiveData<List<Int>> get() = _photoList

2023-07-03 01:20 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreViewModel.kt
> +    }
서버통신 이후 로직까지 고려하면 저게 바람직할 것 같습니다 @KwakEuiJin

2023-07-03 01:53 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/store/apdater/StoreAdapter.kt
> +    class StoreDiffCallback : DiffUtil.ItemCallback<Int>() {
이거 누누형이 만들어준 util에 있습니다 그거 사용하면 편해요!

2023-07-03 02:43 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +        adapter = StoreAdapter { position ->
넵 반영하겠습니다!

2023-07-03 02:43 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +        })
확인하였습니다!

2023-07-03 02:43 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/store/StoreFragment.kt
> +        })
setViewpager에 있는게 맞나 싶었는데 감사합니다!

2023-07-03 02:44 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/store/apdater/StoreAdapter.kt
> +    }
네 알겠습니다!

2023-07-03 06:29 UTC, l2hyunwoo approved these changes
리뷰한것만 반영해주고 머지 가시죠

2023-07-03 06:29 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/store/apdater/StoreAdapter.kt
> +) : ListAdapter<Int, StoreAdapter.StoreViewHolder>(diffCallback) {
```suggestion
    diffCallback: DiffUtil.ItemCallback<Int>,
    private val onItemClicked: (Int) -> Unit,
) : ListAdapter<Int, StoreAdapter.StoreViewHolder>(diffCallback) {
```

패러미터에 람다식이 들어간 웬만한 경우에는 trailing lambda를 만들 수 있게 해주세요. 그래야 줄 인덴팅도 좀 덜고 가독성도 더 올라갑니다!

2023-07-03 06:32 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/store/apdater/StoreAdapter.kt
> +) : ListAdapter<Int, StoreAdapter.StoreViewHolder>(diffCallback) {
네 감사합니당 ㅎㅎ

2023-07-03 06:50 UTC, KwakEuiJin approved these changes

2023-07-03 06:52 UTC, merged