[feature/myPage] myPage 진행상황 공유
TeamPophory/pophory-android pull request #57
Opened 2023-07-03 10:57 UTC by librarywon

## 이슈 코드 

- close #56 

## 📸 스크린샷
<img width="384" alt="스크린샷 2023-07-03 오후 7 56 19" src="https://github.com/TeamPophory/pophory-android/assets/52442547/81c54e7d-01c1-4971-9fe1-09ca17b70707">

## 🍀 관련 이슈
- 아이템이 3개 밖에 불러와지지 않는 문제가 있음

2023-07-03 14:25 UTC, KwakEuiJin requested changes

2023-07-03 14:25 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/data/repository/fake/FakeMyPageInfoRepository.kt
> +}
MyPage관련 Repository Interface를 따로 작성하는 것이 좋아보입니다.

2023-07-03 14:25 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +
onDestroyView에서 null로 다시 리소스 해제를 해주시면 좋을 것 같습니다.

2023-07-03 14:25 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +                }
Uninitialized 내에서 initRecyclerView를 선언하는 것이 좋아보입니다. 
순서는 
initRecyclerView()
viewModel.getMyPageInfo()

2023-07-03 14:25 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +            if (photoList is MyPageInfoState.SuccessPhotos) {
ItemDiffCallback 을 Adapter의 생성자로 외부에서 주입받는 것이 아닌 super의 생성자에서 생성해주어도 괜찮을 것 같습니다. 
@l2hyunwoo 좋은 방법 맞을까요?

2023-07-03 14:25 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageViewModel.kt
> +}
@l2hyunwoo 
Fragment단의 state 구독의 Uninitiialize 에서 getMyPageInfo를 부르는게 좋을까요? 아니면 init 블럭 내에 있는게 좋을까요? 일단 지금은 중복되어있어서 하나는 제거해야하는데 뭐가 좋은지 잘모르겠습니다

2023-07-03 14:25 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/model/MypageInfo.kt
> +    )
mapping되는 부분에서 보니 nonull한 타입으로 반환됩니다. nullable한 타입은 변경해주시면 감사하겠습니다.

2023-07-03 14:57 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/data/repository/fake/FakeMyPageInfoRepository.kt
> +}
확인하였고 반영하였습니다 감사합니다!

2023-07-03 14:59 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +
감사합니다 👍

2023-07-03 15:02 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +                }
반영하였습니다!!

2023-07-03 16:13 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageViewModel.kt
> +}
```
init {
        getMyPageInfo()
    }
```
를 제거하였습니다 !

2023-07-03 16:13 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/model/MypageInfo.kt
> +    )
네 확인하였습니다!

2023-07-03 23:23 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageViewModel.kt
> +}
오호 이유가 무엇인가요!?

2023-07-04 04:24 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageViewModel.kt
> +}
오류를 수정하던 도중 현우형이 지우셔서 이유를 물어보겠습니다!

2023-07-04 04:35 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageViewModel.kt
> +}
일단 레이아웃 에러 해결 도중에 지운거여서 별 이유는 딱히 없습니다.

2023-07-04 05:26 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +        binding.tvMypagePictureCount.text = spannableStringBuilder
로직 정말 잘 구현했어 👍🏻

2023-07-04 05:26 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageViewModel.kt
> +//                }
주석 표기된건 필요 없으면 바로 삭제해줘. 나중에 이게 왜 주석친지 모르는 경우도 발생할 수 있어.

2023-07-04 05:26 UTC, l2hyunwoo commented on app/src/main/res/layout/fragment_mypage.xml
> +                android:layout_height="180dp"
고정 dp, 고정 비율이면 dimension_ratio 였나 그거 쓰면 될 것 같음

2023-07-04 05:30 UTC, l2hyunwoo requested changes
추가 리뷰

2023-07-04 05:30 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/data/repository/fake/FakePhotoRepository.kt
> +
빈줄

2023-07-04 05:30 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +
빈줄

2023-07-04 05:30 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +                            tvMypageFeedEmpty.visibility = View.GONE
isVisible = false 뭐 이런식으로 가도 되지 않을까 싶은데...?

2023-07-04 05:30 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +            if (photoList is MyPageInfoState.SuccessPhotos) {
네 그게 좀더 가독성에 좋을 것 같습니당. @KwakEuiJin cc. @librarywon

2023-07-04 05:30 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +                //TODO intent photo_detail activity
👍🏻

2023-07-04 05:30 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageInfoState.kt
> +    data class Error(val error: Throwable) : MyPageInfoState()
의진이거 보고 참고 한 것 같은데 성공했을때의 data class 네이밍이 저게 들어가는게 맞나 다시 한번 생각해봐. 그리고 이 구조를 사용하는게 좋은지도 생각을 해보고. 왜 내가 Ui State를 이렇게 사용하고 유지보수할 때 어떤 장점이 생기는지에 대해 생각을 해보면 좋을 것 같아

2023-07-04 05:30 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/decorator/GridSpacingItemDecoration.kt
> +}
core common 모듈로 빼자

2023-07-04 06:56 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +        binding.tvMypagePictureCount.text = spannableStringBuilder
감사합니다 ㅎㅎ 😄 뿌듯

2023-07-04 07:02 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/decorator/GridSpacingItemDecoration.kt
> +}
넵 core/common/view/ViewExt에 추가하겠습니다!

2023-07-04 07:04 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +                            tvMypageFeedEmpty.visibility = View.GONE
진행해보겠습니다!

2023-07-04 07:06 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageViewModel.kt
> +//                }
넵 지우도록 하겠습니다!

2023-07-04 07:11 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageInfoState.kt
> +    data class Error(val error: Throwable) : MyPageInfoState()
참고해서 진행하다보니 간과하고 지나간 면이 있었던 것 같습니다.  Ui State에 대해서 더 고민해보겠습니다!

2023-07-04 07:59 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +                            tvMypageFeedEmpty.visibility = View.GONE
이렇게 개선했습니다!

```kotlin
val isNotEmpty = myPageInfoState.data.photos.isNotEmpty()

if(isNotEmpty) {
  myPageAdapter?.submitList(myPageInfoState.data.photos)
}
rvMypage.isVisible = isNotEmpty
ivMypageFeedEmpty.isVisible = !isNotEmpty
tvMypageFeedEmpty.isVisible = !isNotEmpty
```

2023-07-04 12:28 UTC, KwakEuiJin approved these changes
LGTM 🥇

2023-07-04 12:52 UTC, l2hyunwoo approved these changes
한번만...더 수정해줘!

2023-07-04 12:52 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +                    val myPageInfoData = arrayListOf<Any>().apply {
구두로 리뷰함

2023-07-04 12:52 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +
빈줄!

2023-07-04 12:52 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/adapter/MyPageAdapter.kt
> +    ItemDiffCallback<Any>(
이것도 MyPageInfoState로!

2023-07-04 16:23 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/MyPageFragment.kt
> +
제거하였습니다!

2023-07-04 16:23 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/home/mypage/adapter/MyPageAdapter.kt
> +    ItemDiffCallback<Any>(
변경하였습니다!

2023-07-04 17:17 UTC, merged