[feat/album]: Change Flexbox to LinearLayoutManager and Add Hilt
TeamPophory/pophory-android pull request #58
Opened 2023-07-03 14:01 UTC by KwakEuiJin

- close #54 

## 🍀 관련 이슈
- BASE_URL 숨기는 기능 추가해야함
- AuthToken이 아닌 현재는 memberId이기에 리팩터링 필요
- Mapping의 경우 서버측의 photo 상세정보가 내려오면 판단
- 코드만 한번 확인 부탁드립니다

2023-07-03 14:13 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/network/okhttp/AuthInterceptor.kt
> +        return chain.proceed(headerRequest)
요기 소셜로그인으로 바뀌면 Auth로 변경해야함

2023-07-03 14:13 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/network/retrofit/album/RetrofitPhotoNetwork.kt
> +class RetrofitPhotoNetwork @Inject constructor(
숨기는건 논의가 필요하다 생각함

2023-07-03 14:42 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/network/retrofit/album/RetrofitPhotoNetwork.kt
> +class RetrofitPhotoNetwork @Inject constructor(
Local.properties ㄱㄱ

2023-07-03 14:48 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/network/retrofit/album/RetrofitPhotoNetwork.kt
> +class RetrofitPhotoNetwork @Inject constructor(
ㄱㄱㄱ

2023-07-04 04:26 UTC, librarywon approved these changes
LGTM ✨ 많이 배워갑니다!

2023-07-04 04:26 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/album/adapter/AlbumAdapter.kt
> +            AlbumViewType.HORIZONTAL_TYPE.ordinal -> {
이게 멀티 뷰타입 코드이군요 배워가겠습니다!!

2023-07-04 04:27 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/network/retrofit/album/RetrofitPhotoNetwork.kt
> +class RetrofitPhotoNetwork @Inject constructor(
확인하였습니다!

2023-07-04 05:24 UTC, l2hyunwoo requested changes
리뷰 봐주세요

2023-07-04 05:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/model/PhotoItem.kt
> +        val photo: Pair<Photo, Photo>
한 row에 사진이 2개가 온다는건 지금 스펙이긴 하지만, 더 생각을 해보면 한 칸에 3~4개로 늘어난다고 하면 어떻게 대응을 할 수 있을까요?

2023-07-04 05:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/model/PhotoItem.kt
> +        )
밑의 데이터 클래스와 동일하니 중복 코드 통합시키시면 될 것 같습니다.

2023-07-04 05:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/viewholder/FlexBoxLayoutViewHolder.kt
안사용하면 삭제!

2023-07-04 05:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/network/model/PhotoListResponse.kt
> +                    imageUrl = photos?.getOrNull(0)?.imageUrl ?: ""
firstOrNull 이라는 메서드가 있습니다

+) orEmpty() 함수 찾아보세요

2023-07-04 05:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/network/model/PhotoListResponse.kt
> +    //TODO 추후 리팩터링 예정
이럴거면 그냥 

```kotlin
    val first = photos.firstOrNull()
    val second = photos.getOrNull(1)
```

미리 변수 선언해서 사용하면 되지 않을까 싶음

2023-07-04 05:24 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/network/retrofit/album/RetrofitPhotoNetwork.kt
> +    private val networkApi: RetrofitPhotoNetworkApi = Retrofit.Builder()
Retrofit 주입받을 서 사용하는게 객체 생성 비용을 줄일 수 있을 것 같아. 다른 Interface에서도 사용해야하는 친구니까

2023-07-04 05:26 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/di/NetworkModule.kt
> +            .addInterceptor(AuthInterceptor())
ㅋㅎㅋㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎㅋㅎ 바꿔줘~!~!~! Authenticator 공부해보겠슴다

2023-07-04 05:26 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/di/RepositoryBindModule.kt
> +
빈칸 하나당 천원!

2023-07-04 05:27 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/model/PhotoItem.kt
> +        val photo: Pair<Photo, Photo>
그때는 기획분께 조금 많이 힘들다고 말씀드려야할 것 같습니다. 는 농담이고요, 많이 오게되면 list를 통해 하나의 ViewHolder내에 담겨야하는 이미지 아이템의 숫자를 chunk하면 대응될 것 같습니다.

2023-07-04 05:28 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/model/PhotoItem.kt
> +        )
넵! 통합하겠습니다.

2023-07-04 05:33 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/di/NetworkModule.kt
> +            .addInterceptor(AuthInterceptor())
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-07-04 05:37 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/model/PhotoItem.kt
> +        val photo: Pair<Photo, Photo>
ㅇㅇ 제가 보기엔 Pair보단 List가 더 적합한 자료구조인 것 같아요

2023-07-04 09:34 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/network/okhttp/AuthInterceptor.kt
> +        return chain.proceed(headerRequest)
이거 내가 소셜로그인 서버 작업하면서 만들게 지워주실?

2023-07-04 12:13 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/di/RepositoryBindModule.kt
> +
넵 적용하겠습니다!

2023-07-04 12:46 UTC, l2hyunwoo approved these changes
머지 가자잇

2023-07-04 12:46 UTC, merged