[Feature/album detail] bottomSheet와 사진 디테일 추가
TeamPophory/pophory-android pull request #85
Opened 2023-07-06 16:10 UTC by KwakEuiJin

- close #59

2023-07-06 16:36 UTC, l2hyunwoo requested changes

2023-07-06 16:36 UTC, l2hyunwoo commented on app/src/main/res/values/type.xml
> +
삭제

2023-07-06 16:36 UTC, l2hyunwoo commented on app/src/main/res/values/themes.xml
> +        <item name="textAppearanceHeadline2">@style/TextAppearance.Pophory.HeadLine02</item>
textAppearanceHeadlineLarge로 사용하시면 될듯

2023-07-06 16:36 UTC, l2hyunwoo commented on app/src/main/res/layout/modal_bottom_sheet_content.xml
> +        android:textAppearance="@style/TextAppearance.Pophory.ModalText2"
```suggestion
        android:textAppearance="?textAppearanceHeadlineMedium"
```

2023-07-06 16:36 UTC, l2hyunwoo commented on app/src/main/res/layout/modal_bottom_sheet_content.xml
> +        android:textAppearance="@style/TextAppearance.Pophory.ModalText1"
```suggestion
        android:textAppearance="?textAppearanceModalText1"
```

2023-07-07 01:42 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
> +        viewModel.albumSortType.flowWithLifecycle(lifecycle, Lifecycle.State.STARTED).onEach {
```suggestion
        viewModel.albumSortType.flowWithLifecycle(lifecycle).onEach {
```
그냥 이렇게 해도 되지 않나?

2023-07-07 01:42 UTC, l2hyunwoo commented on app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
> +                    getString(R.string.sort_newest)
유틸에 stringOf라고 있지 않나?

2023-07-07 03:13 UTC, librarywon approved these changes
LGTM... 의진아 넌 정말 체고다 ✨ ✨ ✨ ✨ ✨ ✨

2023-07-07 03:13 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/data/network/model/album/PhotoListResponse.kt
> +            }
이렇게 해보는건 어떤가요?

```suggestion
    val orientationType = when {
    width > height -> OrientType.HORIZONTAL
    width < height -> OrientType.VERTICAL
    else -> OrientType.NONE
}

photoDetails.add(
    PhotoDetail(id, studio, takenAt, imageUrl, width, height, orientationType)
)

```

2023-07-07 03:13 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDeleteDialogFragment.kt
> +        @JvmStatic
이 어노테이션은 어떤 역할을 하나요?

2023-07-07 03:13 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
> +                is AlbumListState.Error -> {
이렇게 테그를 활용하는거군요 배웠습니다!

2023-07-07 03:13 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/album/list/viewholder/AlbumViewHolder.kt
> +                crossfade(true)
coil 실망할뻔 휴~~

2023-07-07 03:40 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
> +        viewModel.albumSortType.flowWithLifecycle(lifecycle, Lifecycle.State.STARTED).onEach {
@l2hyunwoo 
기본값이 있군요 확인!!

```
@OptIn(ExperimentalCoroutinesApi::class)
public fun <T> Flow<T>.flowWithLifecycle(
    lifecycle: Lifecycle,
    minActiveState: Lifecycle.State = Lifecycle.State.STARTED
): Flow<T> = callbackFlow {
    lifecycle.repeatOnLifecycle(minActiveState) {
        this@flowWithLifecycle.collect {
            send(it)
        }
    }
    close()
}
```

2023-07-07 03:41 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
> +                    getString(R.string.sort_newest)
오 처음봤슴다

2023-07-07 03:42 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/data/network/model/album/PhotoListResponse.kt
> +            }
개쩔어요 지렸다...

2023-07-07 03:42 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDeleteDialogFragment.kt
> +        @JvmStatic
자바에서도 static처럼 사용할 수 있게 해주는 친구입니당

2023-07-07 03:42 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/list/AlbumListActivity.kt
> +                is AlbumListState.Error -> {
저도... 잘 모르는데 코파일럿이 추천해주었어요 ㅋㅎㅋㅎㅎㅋㅎㅋㅎ

2023-07-07 03:43 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/feature/album/list/viewholder/AlbumViewHolder.kt
> +                crossfade(true)
coil 컨트리뷰트 한번 가시죠

2023-07-07 03:45 UTC, KwakEuiJin commented on app/src/main/java/com/teampophory/pophory/data/network/model/album/PhotoListResponse.kt
> +            }
여기에 또 제가 간과한 부분이 == 일 경우에는 NONE으로 처리되게 해놓았네욥... 해당 부분도 수정해서 처리하도록 하겠습니다

2023-07-07 04:10 UTC, librarywon commented on app/src/main/java/com/teampophory/pophory/feature/album/detail/AlbumDeleteDialogFragment.kt
> +        @JvmStatic
오 또 배워가네요 감사합니다 ㅎㅎ

2023-07-07 05:55 UTC, closed without merging